### ISSUE TITLE
Open Outdoor Style missing markers

### ISSUE THREAD

**Issue by ZedeN1** [OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets#7]
[OS_VTS_3857_Open_Outdoor.json](https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/blob/f462084a0b5f1825f7ae766ff734adb8e8d2aad3/OS_VTS_3857_Open_Outdoor.json) is missing styles for all markers. This is particularly noticeable with railway stations.

See side by side map view with [OS_VTS_3857_Open_Greyscale.json](https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/blob/f462084a0b5f1825f7ae766ff734adb8e8d2aad3/OS_VTS_3857_Open_Greyscale.json)
![image](https://github.com/user-attachments/assets/c2a8c35e-4e63-43eb-9820-f6895b333a42)

And compare the above with the screenshot from [README.md](https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/blob/f462084a0b5f1825f7ae766ff734adb8e8d2aad3/README.md)
![image](https://raw.githubusercontent.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/main/img/ESRI.png)

<details><summary>QGIS About</summary>
<p>

```
QGIS version
3.38.3-Grenoble
QGIS code revision
37f9e6efeec
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.4
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PostgreSQL client version
16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
SpatiaLite version
5.1.0
QWT version
6.1.4
QScintilla2 version
2.14.1
OS version
Ubuntu 24.04.1 LTS
```

</p>
</details>

**Comment by tmnnrs** [comment]
Hi @ZedeN1. Commit [`d9fb4ae`](https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/commit/d9fb4ae075ba07acdcc7a3c8eeb64fb71be83f57) should hopefully resolve this issue.

Unlike the Open Greyscale style (which used a custom set of sprites hosted with the GitHub repo) the Open Outdoor style was previously referencing the source OS Vector Tile API sprite (https://api.os.uk/maps/vector/v1/vts/resources/sprites/sprite). This requires authentication via a project API key (otherwise a 401 "Unauthorised" error would be returned).

Within web mapping libraries (e.g. MapLibre GL JS) this can be handled by a `transformRequest()` callback (see https://labs.os.uk/public/os-data-hub-examples/os-vector-tile-api/vts-example-custom-style). Unfortunately this functionality is not available to QGIS users.

Longer term it is our intention to remove the requirement to authenticate the sprite (+ glyph) requests for OS Vector Tile API in a similar manner to that for the [OS NGD API – Tiles](https://docs.os.uk/osngd/accessing-os-ngd/access-the-os-ngd-api/os-ngd-api-tiles).

**Comment by ZedeN1** [comment]
Thank you, issue is fixed now
